services:
  postgres:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
      POSTGRES_DB: autoflex
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: